services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: dk
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "6300:6400"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: